### ISSUE TITLE
BLOCKPRINT_API_URL not in settings example?

### ISSUE THREAD

**Issue by rocknet** [ethstakersclub/ethstakersclub#13]
Hi there.  Trying out ethstakers club for a custom testnet, I get this error trying to start the worker with celery.

`ImportError: cannot import name 'BLOCKPRINT_API_URL' from 'ethstakersclub.settings' (/root/ethstakersclub/ethstakersclub/settings.py)`

Any ideas appreciated.

**Comment by ethstakersclub** [comment]
Thank you very much for creating the issue.

It appears that we overlooked including the new settings option in the example. As evident from the commit that addresses this, you simply have to insert the following line into your settings.py file.

```python
BLOCKPRINT_API_URL = "https://api.blockprint.sigp.io"
```
