### ISSUE TITLE
Max Validator Count

### ISSUE THREAD

**Issue by JHGrove3** [ethstakersclub/ethstakersclub#2]
Please increase the max validators that can be tracked in the dashboard to 1024. Or even 16,384 if it doesn't impose too much overhead.

200 is a large number, but it's not that different from the beaconcha.in limit.

**Comment by JHGrove3** [comment]
Perhaps I misunderstood the messaging. I was able to enter more than 200 validators to monitor. Is it adding a max of 200 at a time?

**Comment by ethstakersclub** [comment]
Thanks a lot for opening an issue. We weren't sure if there was even demand for monitoring that many validators, so it's great to know that we can work on that.

> Perhaps I misunderstood the messaging. I was able to enter more than 200 validators to monitor. Is it adding a max of 200 at a time?

The message was rather meant for slightly more validators (<300). For that many, we really have to test how many that server can handle at once, but 16000 is most definitely too much. 1000 might be doable with a few optimizations.

Btw: It's currently only returning results for up to 200 validators.

**Comment by ethstakersclub** [comment]
Okay, I looked into it and tried a few optimizations, and it seems like 3000 to 4000 should be possible in the near future.

**Comment by xtc0r** [comment]
Taking into account you want to deploy to other chains as well [reference](https://github.com/ethstakersclub/ethstakersclub/issues/9) I want also suggest to increase the limit as long as we can't stake more than 32 ETH (or any other token) per validator.
For example Lukso deposit leader has >600 validators followed by many >500.  See [here](https://explorer.consensus.mainnet.lukso.network/validators/deposit-leaderboard)

**Comment by xfleeeee** [comment]
Is it possible to try increasing to 256 validators first?

**Comment by ethstakersclub** [comment]
> Is it possible to try increasing to 256 validators first?

No problem. We've already increased the validator limit to 256.

**Comment by xfleeeee** [comment]
I tested it and found that it works perfectly when there are less than 256 validators. Thank you for such a quick response and great work!

**Comment by ethstakersclub** [comment]
Providing a brief update: The recent modifications have been implemented successfully, and we have increased the validator limit to 2000. While I had anticipated a higher number, it's worth noting that the cheapest server, which offers adequate storage, unfortunately cannot maintain response times below ~0.1 seconds for more validators.

Should you require a higher validator limit beyond this point, we invite you to reach out to us via Twitter or email. By doing so, we can accommodate an increase to the limit, potentially up to around 32,000 for your account. Please share the email address you used when signing up with us when you communicate.
