### ISSUE TITLE
Add documentation on how to run locally

### ISSUE THREAD

**Issue by faraggi** [ethstakersclub/ethstakersclub#3]
It would be very useful to have some basic instructions on how to run locally.
This would help and provide ease to add Issues and PRs to the repo.

Related; I see the mention `documentation (coming soon)` but I don't know where to contribute to it.

**Comment by ethstakersclub** [comment]
Thanks a lot. We really appreciate you taking the time to raise these issues.

I've added a basic installation guide and a requirements.txt file. Let me know if you have any questions.

**Comment by faraggi** [comment]
> Thanks a lot. We really appreciate you taking the time to raise these issues.
> 
> I've added a basic installation guide and a requirements.txt file. Let me know if you have any questions.

No problem. I'll gladly help with the project. Its right down my alley.


Are you, by chance, going to ethcc next week? I would love to chat.
